# test_getBlockByHeight.tavern.yaml

---

test_name: This method is used to obtain the block content based on block height.

includes:
  - !include common.yaml

stages:
  - name: Both CurrentBlockHeight and HeaderHash are changing frequently.
    request:
      url: "{service.proto:s}://{service.host:s}:{service.port:d}"
      json:
        jsonrpc: "2.0"
        method: "seele_getBlockByHeight"
        params:
          - 1
          - true
        id: 1

      method: POST
      headers:
        content-type: application/json


    response:
      status_code: 200
      body:
        jsonrpc: '2.0'
        id: 1
        result:
          debts: []
          hash: "0x0000011ec27ecced22fc5fa6c29df6c7f1084e3e85bd0d6abb46f3de67610e63"
          header:
            PreviousBlockHash: "0x71420816a79ee8443ae7405fdc04b7938940211f5779d3a7842073c8398eca82"
            # Creator: "0xe2bbc9fadb4c9d78ad2da944ccb408ff55de3931"
            # StateHash: "0x60ab615b3010eb7f35cdc85e811b22876c0636809c06809030654a55e95bf1ca"
            # TxHash: "0xe800199189634548e10c97e7cc70f79623f0740b4f19872fcf1559a8fbf98295"
