---

test_name: Test mqtt message response


paho-mqtt: &mqtt_spec
  # tls:
  #   enable: true
  connect:
    host: 117.50.16.154
    port: 8000
    timeout: 3
  client:
    transport: websockets
    client_id: tavern-tester

stages:
  - name: step 1 - ping/pong
    mqtt_publish:
      topic: /device/123/ping
      payload: ping
    mqtt_response:
      topic: /device/123/pong
      payload: pong
      timeout: 5
      qos: 1

