---

test_name: Test mqtt message response


paho-mqtt: &mqtt_spec
  tls:
    enable: true
  connect:
    host: iot.eclipse.org
    port: 80
    timeout: 3
  client:
    transport: websockets
    client_id: tavern-tester

# {
#   "jsonrpc": "2.0",
#   "method": "seele_getInfo",
#   "params": [],
#   "id": 1
# }
#


stages:
  - name: step 1 - ping/pong
    mqtt_publish:
      topic: paho/test/single
      payload: "payload"

    mqtt_response:
      topic: paho/test/single
      payload: "payload"
      timeout: 5
      qos: 1
